test.galaxyproject.org/bedtools.yml, test.galaxyproject.org/bedtools.yml.lock, test.galaxyproject.org/cutadapt.yml, test.galaxyproject.org/cutadapt.yml.lock, test.galaxyproject.org/fastqc.yml, test.galaxyproject.org/fastqc.yml.lock
I installed these via Travis on my fork while developing the Travis integration so they are already installed. I have not yet enabled Travis for this repo but will do so and PR another test install to try it out for real after these are merged.
=> test.galaxyproject.org tool install samples

scripts/fix-lockfile.py
=> Automatically convert label in .yml to id in .lock

test.galaxyproject.org/cutadapt.yml.lock, test.galaxyproject.org/fastqc.yml.lock
install versions of qc tools for training workflow testing
=> install versions of  cutadapt, fastqc

usegalaxy.org/transit_hmm.yml, usegalaxy.org/transit_hmm.yml.lock
=> Install transit_hmm by itself.

.ci/repos.conf, .travis.yml
Also move repo config vars to a separate file.
Fixes #27.
=> Fix install DB path

scripts/get_common.sh, scripts/intersect_tool_yaml.py, scripts/split_tool_yml.py
This script will run and create a pairwise intersection list of tools and then split them into category sections into an output directory. (Say common_toolset)
It can be used to update the common_toolset list.
=> Added a get_common.sh script to find usegalaxy.* common toolset.

test.galaxyproject.org/aggregate_fitness.yml, test.galaxyproject.org/aggregate_fitness.yml.lock, test.galaxyproject.org/calculate_fitness.yml, test.galaxyproject.org/calculate_fitness.yml.lock, test.galaxyproject.org/compgenes.yml, test.galaxyproject.org/compgenes.yml.lock, test.galaxyproject.org/compregions.yml, test.galaxyproject.org/compregions.yml.lock, test.galaxyproject.org/compstrains.yml, test.galaxyproject.org/compstrains.yml.lock, test.galaxyproject.org/dataoverview.yml, test.galaxyproject.org/dataoverview.yml.lock, test.galaxyproject.org/regionfitness.yml, test.galaxyproject.org/regionfitness.yml.lock, test.galaxyproject.org/singlefitness.yml, test.galaxyproject.org/singlefitness.yml.lock
- Aggregate fitness v1.0.0
- Calculate Fitness v1.0.0
- Compare Genes v0.1.0
- Compare Regions v0.1.0
- Compare Strains v0.1.0
- Data Overview v0.1.0
- Region Fitness v0.1.0
- Single Fitness v0.1.0
=> Install TnSeq tools by van Opijnen lab on test.

scripts/get_common.sh
=> fix get_common.sh

.ci/jenkins.sh, .ci/tool_sheds_conf.xml, test.galaxyproject.org/dynamic_downsample.yml, test.galaxyproject.org/dynamic_downsample.yml.lock
This installs a tool on test to dynamically downsample a bam file to the specified coverage value.
=> Install dynamic downsampling tool on test.

scripts/split_tool_yml.py
- Normalize using the agreed-upon algorithm
- Drop section ID from base files
- Only drop shed URL if it's the MTS
=> Minor fixes to lock file generation script

.ci/jenkins.sh, usegalaxy.org/fasta_fastq.yml.lock, usegalaxy.org/fastq_quality_control.yml.lock, usegalaxy.org/fetch_sequences_alignments.yml.lock, usegalaxy.org/gatk.yml.lock, usegalaxy.org/genome_diversity.yml.lock, usegalaxy.org/get_data.yml.lock, usegalaxy.org/graph_display_data.yml.lock, usegalaxy.org/iwtomics.yml.lock, usegalaxy.org/join__subtract_and_group.yml.lock, usegalaxy.org/mapping.yml.lock, usegalaxy.org/metagenomic_analysis.yml.lock, usegalaxy.org/mimodd.yml.lock, usegalaxy.org/mothur.yml.lock, usegalaxy.org/motif.yml.lock, usegalaxy.org/multiple_alignments.yml.lock, usegalaxy.org/nanopore.yml.lock, usegalaxy.org/ncbi_blast_.yml.lock
=> Regenerate and update lock files for sections F-N of usegalaxy.org

test.galaxyproject.org/statistics.yml, test.galaxyproject.org/statistics.yml.lock
sklearn_train_test_split
sklearn_model_fit
sklearn_fitted_model_eval
=> add train test split and other 2 tools

test.galaxyproject.org/metagenomic_analysis.yml, test.galaxyproject.org/metagenomic_analysis.yml.lock
Requested by Greg
Homepage: https://benjjneb.github.io/dada2/index.html
=> Install dada2 tool suite on test.

usegalaxy.org/du_novo.yml, usegalaxy.org/du_novo.yml.lock
After #90 was merged and these tools were deployed on test.galaxyproject.org, the authors tested them and have confirmed they work properly. Now I'm proposing they be deployed on Main.
=> Duplex Analysis: Add to usegalaxy.org.

test.galaxyproject.org/metagenomic_analysis.yml.lock
My first time on this, so please let me know if I did something wrong here.  Thanks!  ;)
=> Update dada2 tools with fixes

test.galaxyproject.org/data_managers.yml, test.galaxyproject.org/data_managers.yml.lock
This is part of addressing galaxyproject/usegalaxy-playbook#273
=> Install DADA2 data manager to test.

usegalaxy.org/genome_diversity.yml, usegalaxy.org/genome_diversity.yml.lock, usegalaxy.org/get_data.yml, usegalaxy.org/get_data.yml.lock, usegalaxy.org/mapping.yml, usegalaxy.org/mapping.yml.lock, usegalaxy.org/motif.yml, usegalaxy.org/motif.yml.lock, usegalaxy.org/nanopore.yml, usegalaxy.org/nanopore.yml.lock, usegalaxy.org/ncbi_blast_.yml, usegalaxy.org/ncbi_blast_.yml.lock, usegalaxy.org/sam_bam.yml, usegalaxy.org/sam_bam.yml.lock, usegalaxy.org/statistics.yml, usegalaxy.org/statistics.yml.lock
genome_diversity/get_data/mapping/motif/nanopore/blast/sam_bam and
statistic
=> Sync misc. categories with usegalaxy.eu

usegalaxy.org/annotation.yml, usegalaxy.org/annotation.yml.lock
This pulls just the problematic repo from #102. I've also upgraded Conda to 4.6.14 since that attempt, hopefully this will go better, or at least make it easier to figure out what's gone wrong.
=> Install bp_genbank2gff3 on usegalaxy.org

usegalaxy.org/annotation.yml, usegalaxy.org/annotation.yml.lock
=> Partially sync annotation category with usegalaxy.eu

usegalaxy.org/annotation.yml, usegalaxy.org/annotation.yml.lock
=> Partially sync more of annotation category with usegalaxy.eu

usegalaxy.org/graph_display_data.yml, usegalaxy.org/graph_display_data.yml.lock
Will also need to be added to `sanitize_whitelist`
=> Adding JBrowse@1.16.5+galaxy7 to Main

usegalaxy.org/assembly.yml, usegalaxy.org/assembly.yml.lock, usegalaxy.org/evolution.yml, usegalaxy.org/evolution.yml.lock, usegalaxy.org/genome_diversity.yml, usegalaxy.org/genome_diversity.yml.lock
and update tools in assembly section
=> Install tools in new Evolution section, plus install Bandage

.ci/cvmfs-fuse.conf, .ci/jenkins.sh, test.galaxyproject.org/annotation.yml, test.galaxyproject.org/annotation.yml.lock
Rather than installing directly on the Stratum 0. This makes concurrent builds possible and performs the installs on systems with more resources.
=> Support for installing on Jenkins nodes and copying the results to the Stratum 0

usegalaxy.org/sam_bam.yml.lock
includes sam2interval python 3 fix.
=> Update devteam sam_bam tools

usegalaxy.org/annotation.yml, usegalaxy.org/annotation.yml.lock
Another partial install of #102.
=> Install bgruening/repeat_masker on usegalaxy.org

usegalaxy.org/assembly.yml, usegalaxy.org/assembly.yml.lock
Adding newest version of velvet: https://toolshed.g2.bx.psu.edu/view/devteam/velvet/5da9a0e2fb2d
used in workflow: https://training.galaxyproject.org/training-material/topics/assembly/tutorials/general-introduction/tutorial.html
=> Adding velvet@1.2.10.1

usegalaxy.org/convert_formats.yml.lock
=> Update convert_formats.yml.lock for devteam updates

usegalaxy.org/convert_formats.yml.lock, usegalaxy.org/fasta_fastq.yml.lock, usegalaxy.org/fastq_quality_control.yml.lock, usegalaxy.org/picard.yml.lock
This are the now migrated galaxy_sequence_utils tools and an update to picard
=> Update more devteam tools

usegalaxy.org/annotation.yml.lock, usegalaxy.org/assembly.yml.lock, usegalaxy.org/convert_formats.yml.lock, usegalaxy.org/du_novo.yml.lock, usegalaxy.org/evolution.yml.lock, usegalaxy.org/fastq_quality_control.yml.lock, usegalaxy.org/fetch_sequences_alignments.yml.lock, usegalaxy.org/graph_display_data.yml.lock, usegalaxy.org/mapping.yml.lock, usegalaxy.org/metagenomic_analysis.yml.lock, usegalaxy.org/mothur.yml.lock, usegalaxy.org/motif.yml.lock, usegalaxy.org/multiple_alignments.yml.lock, usegalaxy.org/nanopore.yml.lock, usegalaxy.org/presto.yml.lock, usegalaxy.org/rna_seq.yml.lock, usegalaxy.org/sam_bam.yml.lock, usegalaxy.org/variant_calling.yml.lock, usegalaxy.org/vcf_bcf.yml.lock
Includes poretools and meme fixes.
I know this list is big, but maybe we can use this to see where things fail with such large lists. I think we need to be able to do this so that we can start doing automatic updates.
=> Update all IUC repos

usegalaxy.org/hyphy.yml.lock
=> Update HyPhy to 2.5.7

test.galaxyproject.org/collection_operations.yml, test.galaxyproject.org/collection_operations.yml.lock
Add Split File to Collection tool to test
=> Add Split File to Collection tool to test

usegalaxy.org/evolution.yml, usegalaxy.org/evolution.yml.lock, usegalaxy.org/hyphy.yml, usegalaxy.org/hyphy.yml.lock
=> Add TN93 tool to main

usegalaxy.org/hyphy.yml, usegalaxy.org/hyphy.yml.lock
This also adds a new tool, HyPhy-PRIME
=> Install HyPhy 2.5.8 on usegalaxy.org

usegalaxy.org/get_data.yml.lock
This version retries the prefetch operation up to three times on failure.
=> Install new version of fasterq_dump.

.ci/jenkins.sh
This should resolve the jenkins error in #199
=> Move the database template off PSU architecture and onto github.

test.galaxyproject.org/protein_modeling.yml.lock
Updates springsuite revision, takes two collections as input now.
=> Update springsuite revision

usegalaxy.org/text_manipulation.yml, usegalaxy.org/text_manipulation.yml.lock
Adding `Regex Find And Replace` and `Column Regex Find And Replace` from 
https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/regex_find_replace
Is this correct? Ping @mvdbeek
=> Add regex_find_replace

usegalaxy.org/protein_modeling.yml.lock
This adds additional columns to the result file which contain the identified templates not only the predicted interactions. This information will be used to create 3D models of the predicted protein protein interactions.
=> Update springsuite min-Z filter method

usegalaxy.org/protein_modeling.yml.lock
Reverts galaxyproject/usegalaxy-tools#249
=> Revert "Update springsuite min-Z filter method"

.ci/jenkins.sh
Had completely forgotten about https://github.com/galaxyproject/ephemeris/pull/161
=> Switch back to galaxyproject ephemeris repo

usegalaxy.org/du_novo.yml.lock
Reverts galaxyproject/usegalaxy-tools#262
=> Revert "Update variant analyzer on usegalaxy.org"

usegalaxy.org/du_novo.yml.lock
Reverts galaxyproject/usegalaxy-tools#266
=> Revert "Revert "Update variant analyzer on usegalaxy.org""

usegalaxy.org/graph_display_data.yml.lock
The version in #285 wasn't the latest for some reason.
=> Update JBrowse on usegalaxy.org

usegalaxy.org/fastq_quality_control.yml.lock, usegalaxy.org/mapping.yml.lock, usegalaxy.org/nanopore.yml.lock, usegalaxy.org/sam_bam.yml.lock
So I can make progress on workflow updates.
=> Smaller set of IUC update

usegalaxy.org/fasta_fastq.yml, usegalaxy.org/fasta_fastq.yml.lock
Required for Understanding Barcodes tutorial.
https://training.galaxyproject.org/training-material/topics/transcriptomics/tutorials/scrna-umis/tutorial.html?utm_source=smorgasbord&utm_medium=website&utm_campaign=smorgasbord2021#coupling-our-data-sources
=> Install iuc/umi-tools extract

usegalaxy.org/annotation.yml.lock, usegalaxy.org/assembly.yml.lock, usegalaxy.org/chip_seq.yml.lock, usegalaxy.org/emboss.yml.lock, usegalaxy.org/fastq_quality_control.yml.lock, usegalaxy.org/graph_display_data.yml.lock, usegalaxy.org/mapping.yml.lock, usegalaxy.org/metagenomic_analysis.yml.lock, usegalaxy.org/mothur.yml.lock, usegalaxy.org/nanopore.yml.lock, usegalaxy.org/ncbi_blast_.yml.lock, usegalaxy.org/rna_seq.yml.lock, usegalaxy.org/sam_bam.yml.lock, usegalaxy.org/single_cell.yml.lock, usegalaxy.org/text_manipulation.yml.lock, usegalaxy.org/vcf_bcf.yml.lock
I'll do more tools from other owners as well but this ended up being quite a few so I'll do it in a separate PR.
This should also rebuild the tool cache as I independently restored the `tool_cache_data_path` attribute in `shed_tool_conf.xml`.
=> Update usegalaxy.org IUC/devteam tools

usegalaxy.org/annotation.yml.lock, usegalaxy.org/assembly.yml.lock, usegalaxy.org/chip_seq.yml.lock, usegalaxy.org/emboss.yml.lock, usegalaxy.org/fastq_quality_control.yml.lock, usegalaxy.org/graph_display_data.yml.lock, usegalaxy.org/mapping.yml.lock, usegalaxy.org/metagenomic_analysis.yml.lock, usegalaxy.org/mothur.yml.lock, usegalaxy.org/nanopore.yml.lock, usegalaxy.org/ncbi_blast_.yml.lock, usegalaxy.org/rna_seq.yml.lock, usegalaxy.org/sam_bam.yml.lock, usegalaxy.org/single_cell.yml.lock, usegalaxy.org/text_manipulation.yml.lock, usegalaxy.org/vcf_bcf.yml.lock
This is the same as #312 (reverted the merge and then reverted the reversion for this PR) because that PR was merged before the deployment ran.
=> Update usegalaxy.org IUC/devteam tools (take 2)

usegalaxy.org/hyphy.yml.lock
Also includes HyPhy clade analysis tools.
=> Deploy HyPhy 2.5.31 on usegalaxy.org

usegalaxy.org/hyphy.yml.lock
And if I knew how to type properly, the branch would also say _31 instead of _32
=> Deploy HyPhy 2.5.31+galaxy1 wrappers on usegalaxy.org

cloud/get_data.yml.lock
Last version of this was the 24th revision
=> Add 25th revision of sra_tools

test.galaxyproject.org/statistics.yml, test.galaxyproject.org/statistics.yml.lock
Number 2 PR: statistics section
=> Number 2: Separating Statistics changes into 3 PRs. Statistics changes

test.galaxyproject.org/machine_learning.yml.lock
=> Number 3: Separating Statistics changes into 3 PRs. ML changes

usegalaxy.org/statistics.yml, usegalaxy.org/statistics.yml.lock
Adding tools incrementally, as adding them together causes the Jenkins build to time out.
=> Adding 3 more tools to stats

usegalaxy.org/sam_bam.yml, usegalaxy.org/sam_bam.yml.lock
Hi, 
Would it be possible that the tool clipOverlap (galaxyproject/tools-iuc#3553) is also added to usegalaxy.org?
Many thanks,
Monika
=> add tool clipOverlap to usegalaxy.org

usegalaxy.org/evolution.yml.lock
Done manually, since the python script was not seeing the revision
=> Replace existing version of iqtree with bug fixed version.

usegalaxy.org/single_cell.yml, usegalaxy.org/single_cell.yml.lock, usegalaxy.org/text_manipulation.yml, usegalaxy.org/text_manipulation.yml.lock
For https://github.com/galaxyproject/iwc/pull/64
=> Update and Install missing ebi_gxa tools

.ci/jenkins.sh, test.galaxyproject.org/annotation.yml.lock
This is mostly to test fuse-overlayfs, which appears to be working properly in bullseye
=> Update tools in the annotation section of test.org

usegalaxy.org/single_cell.yml, usegalaxy.org/single_cell.yml.lock
Since EU is down currently, we were (finally) thinking about a backup server. Here are the tools that are missing from .org for the single cell tutorials.
Do I need to split these into individual PRs or is the system ok with multiple tool requests simultaneously?
=> Add single cell tools needed for spanish workshop on usegalaxy.org

usegalaxy.org/variant_calling.yml, usegalaxy.org/variant_calling.yml.lock
Adds the sniffles and jasminesv tools to the .org server
=> add sniffles and jasminesv

usegalaxy.org/pharmacology.yml, usegalaxy.org/pharmacology.yml.lock
Redo #457 for to actually test and deploy the tool... I keep forgetting the flow.
=> add pharmacology section, and pharmcat tool

usegalaxy.org/assembly.yml.lock, usegalaxy.org/mapping.yml.lock, usegalaxy.org/rna_seq.yml, usegalaxy.org/rna_seq.yml.lock
Updates to the latest versions of Minimap, Bionano, and Hifiasm used in the VGP workflows.
=> Request for updating Vgp on main

usegalaxy.org/du_novo.yml.lock
This updates Du Novo on Main.
It addresses the issue with #476.
=> Update Du Novo to 3.0.2.

usegalaxy.org/graph_display_data.yml.lock
Fixes galaxyproject/usegalaxy-playbook#357
=> Update ucsc_custom_track on usegalaxy.org

usegalaxy.org/nanopore.yml.lock
Update Flye up to version 2.9.
=> Update Flye tool v.2.9

.github/pull_request_template.md
This is useful info for both submittesr and @tool-installers.
=> Add basic PR template outlining install process.

usegalaxy.org/rna_analysis__deprecated_.yml.lock
=> Update cuffdiff tool

usegalaxy.org/fastq_quality_control.yml, usegalaxy.org/fastq_quality_control.yml.lock
=> Add FASTQ_info

usegalaxy.org/assembly.yml.lock, usegalaxy.org/extract_features.yml, usegalaxy.org/extract_features.yml.lock
=> VGP project : Addition of Parse Mitochondrial Blast tool, and updates of assembly tools on usegalaxy.org

usegalaxy.org/annotation.yml.lock, usegalaxy.org/assembly.yml.lock, usegalaxy.org/chip_seq.yml.lock, usegalaxy.org/graph_display_data.yml.lock, usegalaxy.org/machine_learning.yml.lock, usegalaxy.org/metagenomic_analysis.yml.lock, usegalaxy.org/pharmacology.yml.lock, usegalaxy.org/rna_seq.yml.lock, usegalaxy.org/single_cell.yml.lock, usegalaxy.org/statistics.yml.lock, usegalaxy.org/text_manipulation.yml.lock
=> Update bgruening tools

usegalaxy.org/chemicaltoolbox.yml.lock
=> Install older chemteam tools for iwc workflows

test.galaxyproject.org/annotation.yml, test.galaxyproject.org/annotation.yml.lock
=> Install maker on test.galaxyproject.org

usegalaxy.org/get_data.yml.lock
=> Update datasets tool again

usegalaxy.org/annotation.yml, usegalaxy.org/annotation.yml.lock
=> Install orfipy into annotation category

usegalaxy.org/du_novo.yml.lock
Tested #509 on the test server (thanks @gallardoalba!) and it seems to be working. I think it's ready to be updated on Main.
=> Update Sequence Content Trimmer on usegalaxy.org.

usegalaxy.org/virology.yml.lock
=> Update Pangolin version 4.0.5

usegalaxy.org/annotation.yml.lock, usegalaxy.org/fasta_fastq.yml.lock
This PR updates cutadapt and BUSCO; this update is required for the VGP workflow.
=> Update cutadapt and BUSCO

usegalaxy.org/chemicaltoolbox.yml.lock, usegalaxy.org/get_data.yml.lock, usegalaxy.org/picard.yml.lock, usegalaxy.org/sam_bam.yml.lock
=> Iwc datasets updates

cloud/collection_operations.yml.lock, cloud/fasta_fastq.yml, cloud/fasta_fastq.yml.lock, cloud/fastq_quality_control.yml.lock, cloud/mapping.yml, cloud/mapping.yml.lock, cloud/rna_seq.yml, cloud/rna_seq.yml.lock, cloud/sam_bam.yml.lock, cloud/single_cell.yml, cloud/single_cell.yml.lock, cloud/text_manipulation.yml.lock
Adding single-cell toolset for the `cloud` suite.
=> [cloud] Add single-cell toolset

usegalaxy.org/assembly.yml, usegalaxy.org/assembly.yml.lock
=> Add smudgeplot tool

usegalaxy.org/proteomics.yml.lock
just a quick update to clear an old issue
@galaxybot test this
=> updates to latest version, fixes #405

usegalaxy.org/datamash.yml.lock
Update Datamash to the latest revision (https://github.com/galaxyproject/tools-iuc/pull/4637), needed for a new tutorial on data manipulation
=> [usegalaxy.org] Update Datamash to latest revision

test.galaxyproject.org/rna_seq.yml.lock
=> Update rnastar on test.galaxyproject.org

usegalaxy.org/assembly.yml.lock
=> update versions of assembly tools on main

test.galaxyproject.org/assembly.yml.lock, usegalaxy.org/extract_features.yml.lock, usegalaxy.org/ncbi_blast_.yml.lock
Update to the latest versions of NCBI blast plus and parse_mito_blast
=> Update to the latest updates of ncbi blast and mito parse

usegalaxy.org/fasta_fastq.yml, usegalaxy.org/fasta_fastq.yml.lock
=> Install remaining UMI tools

usegalaxy.org/multiple_alignments.yml.lock
=> Clustalw: install last update

usegalaxy.org/annotation.yml.lock
=> Orfipy: install tool update

usegalaxy.org/annotation.yml, usegalaxy.org/annotation.yml.lock
This PR installs Nucleolar localization sequence Detector (NoD) https://toolshed.g2.bx.psu.edu/repos/peterjc/clinod
=> Install Nucleolar localization sequence Detector (NoD)

usegalaxy.org/annotation.yml, usegalaxy.org/annotation.yml.lock
Reverts galaxyproject/usegalaxy-tools#547
meant to merge another PR
=> Revert "Install Nucleolar localization sequence Detector (NoD)"

usegalaxy.org/assembly.yml.lock
=> update of gfastats to version 1.3.4

usegalaxy.org/assembly.yml.lock
=> update of yahs and other iuc tools

test.galaxyproject.org/assembly.yml.lock
=> update version of assembly tools on test

usegalaxy.org/graph_display_data.yml.lock
=> Update IUC graph display tools

usegalaxy.org/annotation.yml.lock, usegalaxy.org/bed.yml.lock, usegalaxy.org/chip_seq.yml.lock, usegalaxy.org/convert_formats.yml.lock, usegalaxy.org/datamash.yml.lock, usegalaxy.org/du_novo.yml.lock, usegalaxy.org/evolution.yml.lock, usegalaxy.org/extract_features.yml.lock, usegalaxy.org/fasta_fastq.yml.lock, usegalaxy.org/fastq_quality_control.yml.lock, usegalaxy.org/get_data.yml.lock, usegalaxy.org/graph_display_data.yml.lock, usegalaxy.org/hyphy.yml.lock, usegalaxy.org/mapping.yml.lock, usegalaxy.org/motif.yml.lock, usegalaxy.org/multiple_alignments.yml.lock, usegalaxy.org/nanopore.yml.lock, usegalaxy.org/ncbi_blast_.yml.lock, usegalaxy.org/operate_on_genomic_intervals.yml.lock, usegalaxy.org/picard.yml.lock, usegalaxy.org/rna_analysis__deprecated_.yml.lock, usegalaxy.org/rna_seq.yml.lock, usegalaxy.org/sam_bam.yml.lock, usegalaxy.org/single_cell.yml.lock, usegalaxy.org/statistics.yml.lock, usegalaxy.org/text_manipulation.yml.lock, usegalaxy.org/transposon_insertion_sequencing.yml.lock, usegalaxy.org/variant_calling.yml.lock, usegalaxy.org/vcf_bcf.yml.lock, usegalaxy.org/virology.yml.lock
=> Update most of iuc and devteam tools

usegalaxy.org/rna_seq.yml, usegalaxy.org/rna_seq.yml.lock
=> Install CEMiTool

usegalaxy.org/annotation.yml.lock, usegalaxy.org/assembly.yml.lock, usegalaxy.org/graph_display_data.yml.lock, usegalaxy.org/machine_learning.yml.lock, usegalaxy.org/statistics.yml.lock, usegalaxy.org/text_manipulation.yml.lock
=> Update all bgruening tools

usegalaxy.org/expression_tools.yml, usegalaxy.org/expression_tools.yml.lock
=> Re-install map_param_value

usegalaxy.org/expression_tools.yml, usegalaxy.org/expression_tools.yml.lock
=> Update map_param_value tool

usegalaxy.org/fasta_fastq.yml.lock, usegalaxy.org/rna_seq.yml.lock
=> Update lparsons tools

usegalaxy.org/sam_bam.yml, usegalaxy.org/sam_bam.yml.lock
=> Install revertr2orientationinbam

cloud/bed.yml.lock, cloud/datamash.yml.lock, cloud/fasta_fastq.yml, cloud/fasta_fastq.yml.lock, cloud/get_data.yml.lock, cloud/mapping.yml.lock, cloud/picard.yml.lock, cloud/rna_seq.yml.lock, cloud/rseqc.yml.lock, cloud/sam_bam.yml.lock, cloud/single_cell.yml.lock, cloud/text_manipulation.yml.lock
=> [cloud] Update tools for the Comp Genomics course

usegalaxy.org/chemicaltoolbox.yml.lock, usegalaxy.org/sam_bam.yml.lock
=> Add older tool versions required for IWC workflows

usegalaxy.org/text_manipulation.yml, usegalaxy.org/text_manipulation.yml.lock
=> addition of tool Add column with fixed value to dataset to main

usegalaxy.org/assembly.yml.lock, usegalaxy.org/chemicaltoolbox.yml.lock, usegalaxy.org/graph_display_data.yml.lock, usegalaxy.org/machine_learning.yml.lock, usegalaxy.org/mapping.yml.lock, usegalaxy.org/multiple_alignments.yml.lock, usegalaxy.org/nanopore.yml.lock, usegalaxy.org/proteomics.yml.lock, usegalaxy.org/rna_seq.yml.lock, usegalaxy.org/statistics.yml.lock, usegalaxy.org/text_manipulation.yml.lock
=> Update most tools to newest revisions

usegalaxy.org/assembly.yml.lock, usegalaxy.org/get_data.yml.lock, usegalaxy.org/graph_display_data.yml.lock, usegalaxy.org/proteomics.yml.lock, usegalaxy.org/rna_seq.yml.lock, usegalaxy.org/text_manipulation.yml.lock, usegalaxy.org/variant_calling.yml.lock
=> Update iuc,devteam,bgruening,galaxyp tools

usegalaxy.org/chemicaltoolbox.yml.lock, usegalaxy.org/epigenetics.yml, usegalaxy.org/epigenetics.yml.lock, usegalaxy.org/graph_display_data.yml.lock
=> Update tools 2 12 22

usegalaxy.org/assembly.yml.lock
=> update of assembly tools

usegalaxy.org/fastq_quality_control.yml.lock
=> update of multiqc

usegalaxy.org/rna_seq.yml.lock
=> Update feelnc v0.2 -> 0.2.1

usegalaxy.org/annotation.yml, usegalaxy.org/annotation.yml.lock
This PR installs 5 tools: ReadItAndKeep, Freyja:demix, Freyja:aggregate and plot, Cojac:mutbamscan, Cojac:tabmut
https://toolshed.g2.bx.psu.edu/repos/iuc/read_it_and_keep
https://toolshed.g2.bx.psu.edu/repos/iuc/freyja_demix
https://toolshed.g2.bx.psu.edu/repos/iuc/freyja_aggregate_plot
https://toolshed.g2.bx.psu.edu/repos/iuc/cooc_mutbamscan
https://toolshed.g2.bx.psu.edu/repos/iuc/cooc_tabmut
=> install tools: ReadItAndKeep, Freyja, Cojac

usegalaxy.org/genome_diversity.yml, usegalaxy.org/genome_diversity.yml.lock
=> Install iuc/raxml on .org

usegalaxy.org/single_cell.yml.lock
=> Update ebi-gxa tools

usegalaxy.org/graph_display_data.yml.lock
=> Update IUC tools in Graph/Display data on .org

usegalaxy.org/planttribes.yml.lock
=> Update PlantTribes tools on .org

usegalaxy.org/single_cell.yml, usegalaxy.org/single_cell.yml.lock
TODO: Please can you add these tools that are needed for some of the GTN tutorials?
=> Add tools for MuSiC and Cell Cycle tutorials

usegalaxy.org/assembly.yml, usegalaxy.org/assembly.yml.lock
=> Install latest revision of velvet

usegalaxy.org/variant_calling.yml, usegalaxy.org/variant_calling.yml.lock
=> Install DeepVariant on usegalaxy.org

cloud/expressiontools.yml, cloud/expressiontools.yml.lock, cloud/fastq_quality_control.yml.lock, cloud/sam_bam.yml, cloud/sam_bam.yml.lock
=> [cloud] Add missing tools for IWC RNA-Seq_pe WF

cloud/convert_formats.yml, cloud/convert_formats.yml.lock, cloud/datamash.yml.lock, cloud/fasta_fastq.yml, cloud/fasta_fastq.yml.lock, cloud/fastq_quality_control.yml.lock, cloud/graph_display_data.yml, cloud/graph_display_data.yml.lock, cloud/mapping.yml.lock, cloud/picard.yml.lock, cloud/rna_seq.yml, cloud/rna_seq.yml.lock, cloud/sam_bam.yml, cloud/sam_bam.yml.lock, cloud/text_manipulation.yml.lock, cloud/variant_calling.yml.lock
=> [cloud] Add and update tools for RNA-Seq and variant calling

cloud/gemini.yml, cloud/gemini.yml.lock, cloud/graph_display_data.yml.lock, cloud/rna_seq.yml, cloud/rna_seq.yml.lock, cloud/text_manipulation.yml, cloud/text_manipulation.yml.lock, cloud/variant_calling.yml.lock, cloud/vcf_bcf.yml.lock
=> [cloud] Add several more tools/versions for RNA seq and VC

usegalaxy.org/annotation.yml.lock, usegalaxy.org/assembly.yml.lock, usegalaxy.org/bed.yml.lock, usegalaxy.org/chemicaltoolbox.yml.lock, usegalaxy.org/datamash.yml.lock, usegalaxy.org/epigenetics.yml.lock, usegalaxy.org/get_data.yml.lock, usegalaxy.org/graph_display_data.yml.lock, usegalaxy.org/hyphy.yml.lock, usegalaxy.org/mapping.yml.lock, usegalaxy.org/metagenomic_analysis.yml.lock, usegalaxy.org/multiple_alignments.yml.lock, usegalaxy.org/nanopore.yml.lock, usegalaxy.org/picard.yml.lock, usegalaxy.org/rna_seq.yml.lock, usegalaxy.org/rseqc.yml.lock, usegalaxy.org/sam_bam.yml.lock, usegalaxy.org/text_manipulation.yml.lock, usegalaxy.org/variant_calling.yml.lock, usegalaxy.org/vcf_bcf.yml.lock, usegalaxy.org/virology.yml.lock
=> Update iuc,bgruening,devteam,nilesh tools

scripts/merge_versions.py, usegalaxy.org/annotation.yml, usegalaxy.org/annotation.yml.lock, usegalaxy.org/assembly.yml.lock, usegalaxy.org/chemicaltoolbox.yml.lock, usegalaxy.org/convert_formats.yml.lock, usegalaxy.org/datamash.yml.lock, usegalaxy.org/emboss.yml.lock, usegalaxy.org/fasta_fastq.yml.lock, usegalaxy.org/fastq_quality_control.yml.lock, usegalaxy.org/graph_display_data.yml.lock, usegalaxy.org/machine_learning.yml.lock, usegalaxy.org/mapping.yml.lock, usegalaxy.org/metagenomic_analysis.yml.lock, usegalaxy.org/nanopore.yml.lock, usegalaxy.org/operate_on_genomic_intervals.yml.lock, usegalaxy.org/proteomics.yml.lock, usegalaxy.org/rna_analysis__deprecated_.yml.lock, usegalaxy.org/rna_seq.yml.lock, usegalaxy.org/single_cell.yml, usegalaxy.org/single_cell.yml.lock, usegalaxy.org/text_manipulation.yml, usegalaxy.org/text_manipulation.yml.lock, usegalaxy.org/virology.yml.lock
This is part 1, part 2 will install tools that are not currently installed.
=> Update versions of currently installed tools for all versions found in GTN tutorials that will be used in Smorg 3

scripts/steal_sections.py, usegalaxy.org/biodiversity_data_exploration.yml, usegalaxy.org/biodiversity_data_exploration.yml.lock, usegalaxy.org/chemicaltoolbox.yml.lock, usegalaxy.org/compute_indicators_for_satellite_remote_sensing.yml, usegalaxy.org/compute_indicators_for_satellite_remote_sensing.yml.lock, usegalaxy.org/deeptools.yml.lock, usegalaxy.org/gemini.yml, usegalaxy.org/gemini.yml.lock, usegalaxy.org/get_data.yml, usegalaxy.org/get_data.yml.lock, usegalaxy.org/graph_display_data.yml.lock, usegalaxy.org/mapping.yml.lock, usegalaxy.org/proteomics.yml.lock, usegalaxy.org/rna_seq.yml, usegalaxy.org/rna_seq.yml.lock, usegalaxy.org/single_cell.yml, usegalaxy.org/single_cell.yml.lock, usegalaxy.org/text_manipulation.yml.lock, usegalaxy.org/variant_calling.yml.lock
This is everything that was listed as missing after attempting to run all the testable workflows.
=> More Smorg3 tools

usegalaxy.org/proteomics.yml.lock, usegalaxy.org/text_manipulation.yml.lock
In particular for a fix in `regexColumn1`
=> Update galaxyp tools

.ci/jenkins.sh, usegalaxy.org/sam_bam.yml, usegalaxy.org/sam_bam.yml.lock
Most importantly `bamtools_split_ref` per @wm75 for https://training.galaxyproject.org/training-material/topics/variant-analysis/tutorials/aiv-analysis/tutorial.html
=> Add additional bamtools tools

usegalaxy.org/annotation.yml, usegalaxy.org/annotation.yml.lock, usegalaxy.org/rna_seq.yml, usegalaxy.org/rna_seq.yml.lock
This PR Includes three tools, required for the GTN training.
=> Add tools required for differential isoform training

usegalaxy.org/annotation.yml.lock, usegalaxy.org/mapping.yml.lock, usegalaxy.org/rna_seq.yml.lock, usegalaxy.org/text_manipulation.yml.lock, usegalaxy.org/training_metabolomics.yml.lock, usegalaxy.org/virology.yml.lock
=> Update all IUC tools

usegalaxy.org/convert_formats.yml.lock, usegalaxy.org/fastq_quality_control.yml.lock, usegalaxy.org/mapping.yml.lock
=> update devteam tools

usegalaxy.org/annotation.yml.lock, usegalaxy.org/assembly.yml.lock, usegalaxy.org/convert_formats.yml.lock, usegalaxy.org/fasta_fastq.yml.lock, usegalaxy.org/fastq_quality_control.yml.lock, usegalaxy.org/graph_display_data.yml.lock, usegalaxy.org/machine_learning.yml.lock, usegalaxy.org/mapping.yml.lock, usegalaxy.org/metagenomic_analysis.yml.lock, usegalaxy.org/multiple_alignments.yml.lock, usegalaxy.org/proteomics.yml.lock, usegalaxy.org/rna_seq.yml.lock, usegalaxy.org/single_cell.yml.lock, usegalaxy.org/statistics.yml.lock, usegalaxy.org/text_manipulation.yml.lock, usegalaxy.org/training_metabolomics.yml.lock, usegalaxy.org/virology.yml.lock
=> Update tools 23 08 30

usegalaxy.org/assembly.yml.lock, usegalaxy.org/epigenetics.yml.lock, usegalaxy.org/mapping.yml.lock, usegalaxy.org/rna_seq.yml.lock
=> Update tools 23 09 06

usegalaxy.org/proteomics.yml, usegalaxy.org/proteomics.yml.lock
=> Install tools for MetaProSIP OpenMS workflow

usegalaxy.org/get_data.yml.lock, usegalaxy.org/graph_display_data.yml.lock, usegalaxy.org/machine_learning.yml.lock, usegalaxy.org/metagenomic_analysis.yml.lock, usegalaxy.org/nanopore.yml.lock, usegalaxy.org/picard.yml.lock, usegalaxy.org/rna_seq.yml.lock, usegalaxy.org/statistics.yml.lock, usegalaxy.org/text_manipulation.yml.lock, usegalaxy.org/variant_calling.yml.lock
=> Update various tools

usegalaxy.org/get_data.yml.lock, usegalaxy.org/rna_seq.yml.lock, usegalaxy.org/single_cell.yml, usegalaxy.org/single_cell.yml.lock
=> add baredSC (and update iuc)

usegalaxy.org/annotation.yml.lock, usegalaxy.org/metagenomic_analysis.yml, usegalaxy.org/metagenomic_analysis.yml.lock
two new tools, two updated ones
=> install mash and mash_sketch and update two IUC tools

usegalaxy.org/deeptools.yml.lock, usegalaxy.org/graph_display_data.yml.lock, usegalaxy.org/machine_learning.yml.lock, usegalaxy.org/metagenomic_analysis.yml.lock, usegalaxy.org/statistics.yml.lock, usegalaxy.org/text_manipulation.yml.lock
Reverts galaxyproject/usegalaxy-tools#639
=> Revert "Update devteam tools"

usegalaxy.org/annotation.yml, usegalaxy.org/annotation.yml.lock
=> Add iuc/mitos2 to .org

usegalaxy.org/annotation.yml.lock, usegalaxy.org/assembly.yml.lock, usegalaxy.org/chip_seq.yml.lock, usegalaxy.org/fasta_fastq.yml.lock, usegalaxy.org/get_data.yml.lock, usegalaxy.org/graph_display_data.yml.lock, usegalaxy.org/machine_learning.yml.lock, usegalaxy.org/metagenomic_analysis.yml.lock, usegalaxy.org/multiple_alignments.yml.lock, usegalaxy.org/ncbi_blast_.yml.lock, usegalaxy.org/rna_seq.yml.lock, usegalaxy.org/single_cell.yml.lock, usegalaxy.org/statistics.yml.lock
Reverts galaxyproject/usegalaxy-tools#650
=> Revert "Update tools"

usegalaxy.org/annotation.yml.lock, usegalaxy.org/single_cell.yml.lock
=> Update busco and single cell tools

usegalaxy.org/annotation.yml.lock, usegalaxy.org/single_cell.yml.lock, usegalaxy.org/text_manipulation.yml, usegalaxy.org/text_manipulation.yml.lock
add a new tool that is used in iwc
=> add concatenate_multiple_datasets

usegalaxy.org/annotation.yml.lock, usegalaxy.org/assembly.yml.lock, usegalaxy.org/genome_diversity.yml.lock, usegalaxy.org/get_data.yml.lock, usegalaxy.org/metagenomic_analysis.yml.lock, usegalaxy.org/ncbi_blast_.yml.lock, usegalaxy.org/sam_bam.yml.lock, usegalaxy.org/single_cell.yml.lock
owners: artbio bgruening chemteam csbl devteam galaxyp iuc lldelisle lparsons nml
What I did which could be automated:
```bash
python3 -m venv .venv
. .venv/bin/activate
pip install -r requirements.txt
workflow-to-tools -w $(find ../iwc/workflows/ -name "*ga") -o all_tools.yml
owners=$(grep owner all_tools.yml | sort | uniq | awk '{print $2}')
rm all_tools.yml 
for owner in $owners; do make TOOLSET=usegalaxy.org OWNER=$owner update-trusted; done
```
=> 20231121 update owners of tools of iwc

README.md, usegalaxy.org/single_cell.yml, usegalaxy.org/single_cell.yml.lock
Add velocyto and cite-seq-count
=> Add single cell tools

usegalaxy.org/sequence_contamination_filtering.yml, usegalaxy.org/sequence_contamination_filtering.yml.lock
Adding the NCBI FCS GX tool into a new Sequence Contamination Filtering section.
=> adding ncbi_fcs_gx tool

usegalaxy.org/metagenomic_analysis.yml, usegalaxy.org/metagenomic_analysis.yml.lock
=> Add MetaBAT2

usegalaxy.org/metagenomic_analysis.yml, usegalaxy.org/metagenomic_analysis.yml.lock
=> Install megahit_contig2fastg

usegalaxy.org/annotation.yml.lock, usegalaxy.org/assembly.yml.lock, usegalaxy.org/chip_seq.yml.lock, usegalaxy.org/convert_formats.yml.lock, usegalaxy.org/data_managers.yml.lock, usegalaxy.org/expression_tools.yml, usegalaxy.org/expression_tools.yml.lock, usegalaxy.org/graph_display_data.yml.lock, usegalaxy.org/metagenomic_analysis.yml.lock, usegalaxy.org/rna_seq.yml.lock, usegalaxy.org/seqtk.yml.lock, usegalaxy.org/single_cell.yml.lock
=> Update tools 24 01

usegalaxy.org/assembly.yml.lock, usegalaxy.org/single_cell.yml.lock
=> update iuc 20231201

usegalaxy.org/data_managers.yml, usegalaxy.org/data_managers.yml.lock
=> Install kraken2, bracken and mapseq data managers

usegalaxy.org/bbtools.yml, usegalaxy.org/bbtools.yml.lock
=> Install BBTools suite

usegalaxy.org/fasta_fastq.yml.lock
=> update cutadapt on main 

usegalaxy.org/rna_seq.yml, usegalaxy.org/rna_seq.yml.lock
=> add trinity_samples_qccheck

usegalaxy.org/qiime2.yml, usegalaxy.org/qiime2.yml.lock
=> qiime - rename upper to lower, that is the name of the repo and jenkins errored

usegalaxy.org/annotation.yml.lock, usegalaxy.org/assembly.yml.lock, usegalaxy.org/bbtools.yml.lock, usegalaxy.org/fastq_quality_control.yml.lock, usegalaxy.org/graph_display_data.yml.lock, usegalaxy.org/mapping.yml.lock, usegalaxy.org/metagenomic_analysis.yml.lock, usegalaxy.org/ncbi_blast_.yml.lock, usegalaxy.org/rna_seq.yml.lock
=> update iuc tools on main

usegalaxy.org/convert_formats.yml, usegalaxy.org/convert_formats.yml.lock
=> Install wig_to_bigwig from TS

usegalaxy.org/convert_formats.yml, usegalaxy.org/convert_formats.yml.lock
=> Install bam2fastx

usegalaxy.org/assembly.yml, usegalaxy.org/assembly.yml.lock, usegalaxy.org/metagenomic_analysis.yml, usegalaxy.org/metagenomic_analysis.yml.lock
closes https://github.com/galaxyproject/usegalaxy-tools/issues/691 https://github.com/galaxyproject/usegalaxy-tools/issues/685
=> install rnaquast and metabat2_jgi_summarize_bam_contig_depths

usegalaxy.org/assembly.yml, usegalaxy.org/assembly.yml.lock
=> Install iuc/pretext_graph on Main

usegalaxy.org/chemicaltoolbox.yml, usegalaxy.org/chemicaltoolbox.yml.lock
supersedes https://github.com/galaxyproject/usegalaxy-tools/pull/566
=> add gmx_rmsf and gmx_rmsd tools to main

usegalaxy.org/protein_modeling.yml, usegalaxy.org/protein_modeling.yml.lock
already installed, this PR is for consistency
https://usegalaxy.org/?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fguerler%2Fdbkit%2Fdbkit_create%2F0.1.1&version=latest
=> add dbkit, this is already installed on Main

usegalaxy.org/annotation.yml.lock, usegalaxy.org/assembly.yml.lock, usegalaxy.org/convert_formats.yml.lock, usegalaxy.org/data_managers.yml.lock, usegalaxy.org/fasta_fastq.yml.lock, usegalaxy.org/get_data.yml.lock, usegalaxy.org/graph_display_data.yml.lock, usegalaxy.org/mapping.yml.lock, usegalaxy.org/metagenomic_analysis.yml.lock, usegalaxy.org/multiple_alignments.yml.lock, usegalaxy.org/nanopore.yml.lock, usegalaxy.org/ncbi_blast_.yml.lock, usegalaxy.org/picard.yml.lock, usegalaxy.org/proteomics.yml.lock, usegalaxy.org/qiime2.yml.lock, usegalaxy.org/rna_seq.yml.lock, usegalaxy.org/sam_bam.yml.lock, usegalaxy.org/single_cell.yml.lock, usegalaxy.org/text_manipulation.yml.lock, usegalaxy.org/transposon_insertion_sequencing.yml.lock, usegalaxy.org/variant_calling.yml.lock, usegalaxy.org/virology.yml.lock
=> Update trusted tools

usegalaxy.org/convert_formats.yml.lock, usegalaxy.org/fasta_fastq.yml.lock
=> update cutadapt to 4.7 and replace broken version of bam2fastx on usegalaxy.org

usegalaxy.org/proteomics.yml, usegalaxy.org/proteomics.yml.lock
Adds both colabfold tools to org
=> add colabfold to org

.ci/jenkins.sh, usegalaxy.org/text_manipulation.yml.lock
=> update text processing tools on main

usegalaxy.org/annotation.yml.lock, usegalaxy.org/convert_formats.yml.lock, usegalaxy.org/data_managers.yml.lock, usegalaxy.org/epigenetics.yml.lock, usegalaxy.org/evolution.yml.lock, usegalaxy.org/get_data.yml.lock, usegalaxy.org/graph_display_data.yml.lock, usegalaxy.org/machine_learning.yml.lock, usegalaxy.org/mapping.yml.lock, usegalaxy.org/metagenomic_analysis.yml.lock, usegalaxy.org/multiple_alignments.yml.lock, usegalaxy.org/nanopore.yml.lock, usegalaxy.org/ncbi_blast_.yml.lock, usegalaxy.org/picard.yml.lock, usegalaxy.org/rna_seq.yml.lock, usegalaxy.org/rseqc.yml.lock, usegalaxy.org/sam_bam.yml.lock, usegalaxy.org/single_cell.yml.lock, usegalaxy.org/training_metabolomics.yml.lock, usegalaxy.org/transposon_insertion_sequencing.yml.lock, usegalaxy.org/variant_calling.yml.lock, usegalaxy.org/virology.yml.lock
=> Update trusted owner tools

usegalaxy.org/mapping.yml, usegalaxy.org/mapping.yml.lock
=> adding segalign tool

cloud/machine_learning.yml, cloud/machine_learning.yml.lock
=> [cloud] Add ML section

usegalaxy.org/mapping.yml.lock
=> updating segalign

usegalaxy.org/text_manipulation.yml.lock
This should have happened in #709, I don't know what happened there.
=> Retry install of latest text_processing

usegalaxy.org/fasta_fastq.yml.lock
=> Update of cutadapt to version 4.8+galaxy0

usegalaxy.org/mapping.yml.lock
=> Updated Segalign with updates for pulsar bug

usegalaxy.org/assembly.yml, usegalaxy.org/assembly.yml.lock
=> Install pairtools suite

usegalaxy.org/mapping.yml, usegalaxy.org/mapping.yml.lock
=> adding batched_lastz

usegalaxy.org/metagenomic_analysis.yml, usegalaxy.org/metagenomic_analysis.yml.lock
=> Install bracken

usegalaxy.org/mapping.yml.lock
=> new batched lastz

usegalaxy.org/mapping.yml.lock
=> new version of segalign that natively supports gzipped fasta

usegalaxy.org/mapping.yml.lock
=> segalign update

.ci/repos.conf
=> Update Main stratum0 to cvmfs0-psu1

usegalaxy.org/annotation.yml, usegalaxy.org/annotation.yml.lock, usegalaxy.org/multiple_alignments.yml, usegalaxy.org/multiple_alignments.yml.lock
=> Install mashmap and windowmasker

usegalaxy.org/annotation.yml, usegalaxy.org/annotation.yml.lock, usegalaxy.org/mapping.yml, usegalaxy.org/mapping.yml.lock
=> Install miniprot and winnowmap

usegalaxy.org/annotation.yml, usegalaxy.org/annotation.yml.lock, usegalaxy.org/assembly.yml, usegalaxy.org/assembly.yml.lock, usegalaxy.org/convert_formats.yml, usegalaxy.org/convert_formats.yml.lock, usegalaxy.org/metagenomic_analysis.yml, usegalaxy.org/metagenomic_analysis.yml.lock
=> Add tools for bacterial assembly workflows

usegalaxy.org/sam_bam.yml, usegalaxy.org/sam_bam.yml.lock
=> Install mosdepth

usegalaxy.org/chemicaltoolbox.yml, usegalaxy.org/chemicaltoolbox.yml.lock
=> add 3 new psp tools

usegalaxy.org/single_cell.yml, usegalaxy.org/single_cell.yml.lock
=> Install ebi-gxa single-cell tools

usegalaxy.org/annotation.yml, usegalaxy.org/annotation.yml.lock
=> Install compleasm on main 

README.md
=> suggest make fix for new tool

.ci/jenkins.sh
=> Don't clean/fix conda

usegalaxy.org/metagenomic_analysis.yml, usegalaxy.org/metagenomic_analysis.yml.lock
Fixes https://github.com/galaxyproject/usegalaxy-tools/issues/778
=> Add kraken tools

usegalaxy.org/mapping.yml.lock
Updating to latest version of segalign
=> Updating to latest version of segalign

usegalaxy.org/mapping.yml.lock
updated to latest version of segalign and batched_lastz
=> updated to latest version of segalign and batched_lastz

usegalaxy.org/annotation.yml.lock, usegalaxy.org/fasta_fastq.yml.lock, usegalaxy.org/fastq_quality_control.yml.lock, usegalaxy.org/graph_display_data.yml.lock, usegalaxy.org/mapping.yml.lock, usegalaxy.org/metagenomic_analysis.yml.lock, usegalaxy.org/text_manipulation.yml.lock, usegalaxy.org/training_metabolomics.yml.lock, usegalaxy.org/variant_calling.yml.lock, usegalaxy.org/vcf_bcf.yml.lock
Reverts galaxyproject/usegalaxy-tools#794
=> Revert "Update all repos 2024-08-12"

usegalaxy.org/annotation.yml, usegalaxy.org/annotation.yml.lock, usegalaxy.org/filter_and_sort.yml, usegalaxy.org/filter_and_sort.yml.lock
=> add iuc bigwig_outlier_bed and microsatbed

usegalaxy.org/annotation.yml.lock, usegalaxy.org/fasta_fastq.yml.lock, usegalaxy.org/fastq_quality_control.yml.lock, usegalaxy.org/graph_display_data.yml.lock, usegalaxy.org/mapping.yml.lock, usegalaxy.org/metagenomic_analysis.yml.lock, usegalaxy.org/text_manipulation.yml.lock, usegalaxy.org/training_metabolomics.yml.lock, usegalaxy.org/variant_calling.yml.lock, usegalaxy.org/vcf_bcf.yml.lock
This is https://github.com/galaxyproject/usegalaxy-tools/pull/794 again
=> Install missing repos

usegalaxy.org/variant_calling.yml, usegalaxy.org/variant_calling.yml.lock
Adds the Arriba tools from tools-iuc.
=> Add Arriba tools.

usegalaxy.org/proteomics.yml.lock
=> Update ColabFold tools

usegalaxy.org/annotation.yml, usegalaxy.org/annotation.yml.lock
=> adding NCBI EGPAx

usegalaxy.org/sequence_contamination_filtering.yml.lock
Update ncbi_fcs_gx to version 0.5.4
=> add latest version of ncbi_fcs_gx

usegalaxy.org/convert_formats.yml, usegalaxy.org/convert_formats.yml.lock, usegalaxy.org/mapping.yml, usegalaxy.org/mapping.yml.lock
=> install 4 ucsc tools

usegalaxy.org/convert_formats.yml, usegalaxy.org/convert_formats.yml.lock, usegalaxy.org/mapping.yml, usegalaxy.org/mapping.yml.lock
=> add chainpreenet and axttomaf from ucsc

usegalaxy.org/mapping.yml, usegalaxy.org/mapping.yml.lock
adding kegalign (segalign replacement)
=> adding kegalign (segalign replacement)

usegalaxy.org/mapping.yml, usegalaxy.org/mapping.yml.lock
=> install ucsc chainnet on main

usegalaxy.org/mapping.yml, usegalaxy.org/mapping.yml.lock
Reverts galaxyproject/usegalaxy-tools#820
this has not been installed properly on usegalaxy.org
=> Revert "install ucsc chainnet on main"

usegalaxy.org/mapping.yml, usegalaxy.org/mapping.yml.lock
=> add ucsc chainnet to main

usegalaxy.org/mapping.yml, usegalaxy.org/mapping.yml.lock
=> add netsyntenic to main

cloud/assembly.yml, cloud/assembly.yml.lock, cloud/bed.yml.lock, cloud/collection_operations.yml, cloud/collection_operations.yml.lock, cloud/convert_formats.yml.lock, cloud/datamash.yml.lock, cloud/deeptools.yml.lock, cloud/expressiontools.yml.lock, cloud/fasta_fastq.yml.lock, cloud/fastq_quality_control.yml.lock, cloud/gemini.yml.lock, cloud/get_data.yml.lock, cloud/graph_display_data.yml.lock, cloud/machine_learning.yml.lock, cloud/mapping.yml.lock, cloud/multiple_alignments.yml.lock, cloud/nanopore.yml.lock, cloud/pharmacology.yml.lock, cloud/picard.yml.lock, cloud/qiime2.yml.lock, cloud/rna_seq.yml, cloud/rna_seq.yml.lock, cloud/sam_bam.yml.lock, cloud/single_cell.yml, cloud/single_cell.yml.lock, cloud/text_manipulation.yml.lock, cloud/variant_calling.yml.lock, cloud/vcf_bcf.yml.lock, cloud/virology.yml.lock
Updating many tool versions in the _cloud_ toolbox.
=> [cloud] Update cloud toolbox

usegalaxy.org/mapping.yml, usegalaxy.org/mapping.yml.lock
=> add ucsc netfilter to main

usegalaxy.org/convert_formats.yml, usegalaxy.org/convert_formats.yml.lock
=> install nettoaxt on org

usegalaxy.org/annotation.yml, usegalaxy.org/annotation.yml.lock
.org part of https://github.com/galaxyproject/usegalaxy-tools/pull/826
=> add tools from  Bacterial Genome Annotation tutorial  to org

usegalaxy.org/assembly.yml, usegalaxy.org/assembly.yml.lock
These will need TPV rules and the container won't be built until the next planemo-monitor run.
=> Install split meryl tools

usegalaxy.org/metagenomic_analysis.yml, usegalaxy.org/metagenomic_analysis.yml.lock
=> Install phyloseq tools

usegalaxy.org/annotation.yml, usegalaxy.org/annotation.yml.lock, usegalaxy.org/graph_display_data.yml.lock
=> Install AGAT

usegalaxy.org/sequence_contamination_filtering.yml.lock
=> updating to latest version of NCBI FCS GX

usegalaxy.org/annotation.yml.lock
=> bumping version of egapx

usegalaxy.org/metagenomic_analysis.yml, usegalaxy.org/metagenomic_analysis.yml.lock
DB is hopefully published successfully on CVMFS.
=> Install gtdbtk_classify_wf on Main

usegalaxy.org/annotation.yml, usegalaxy.org/annotation.yml.lock
Adds the Optitype tool to annotation.yml.
=> Add Optitype tool.

usegalaxy.org/proteomics.yml, usegalaxy.org/proteomics.yml.lock
Add `pepquery`, `pepquery2`, `pepquery2_show_sets`, and `pepquery2_index` to `proteomics.yml`.
=> Add PepQuery and PepQuery2 tools.

usegalaxy.org/metagenomic_analysis.yml, usegalaxy.org/metagenomic_analysis.yml.lock
=> Add metagenomic tools

Makefile, cloud/assembly.yml, cloud/assembly.yml.lock, cloud/fasta_fastq.yml.lock, cloud/fastq_quality_control.yml.lock, cloud/graph_display_data.yml.lock, cloud/nanopore.yml.lock, cloud/qiime2.yml.lock, cloud/rna_seq.yml, cloud/rna_seq.yml.lock, cloud/rseqc.yml.lock, cloud/single_cell.yml.lock, cloud/variant_calling.yml, cloud/variant_calling.yml.lock, cloud/vcf_bcf.yml.lock, scripts/fix_lockfile.py
=> [cloud] Update cloud toolset

usegalaxy.org/annotation.yml.lock
=> updating to latest egapx

usegalaxy.org/sequence_contamination_filtering.yml.lock
=> Update NCBI FCS-GX

usegalaxy.org/metagenomic_analysis.yml, usegalaxy.org/metagenomic_analysis.yml.lock, usegalaxy.org/nanopore.yml.lock, usegalaxy.org/rna_analysis.yml, usegalaxy.org/rna_analysis.yml.lock
=> Install mgnify tools

usegalaxy.org/get_data.yml, usegalaxy.org/get_data.yml.lock, usegalaxy.org/proteomics.yml, usegalaxy.org/proteomics.yml.lock, usegalaxy.org/single_cell.yml, usegalaxy.org/single_cell.yml.lock
=> Install tools for metaproteomics IWC workflows

usegalaxy.org/assembly.yml, usegalaxy.org/assembly.yml.lock
=> adding HalfDeep

usegalaxy.org/machine_learning.yml, usegalaxy.org/machine_learning.yml.lock
With a comprehensive suite of tools, Galaxy-PyCaret enables users to perform complex tasks such as data preprocessing, model selection, and evaluation in a single intuitive interface. It is designed to be powerful and robust for both beginners and advanced users. Whether you are exploring data for insights, building predictive models, or deploying them to production, Galaxy-PyCaret provides a streamlined workflow that saves time.
=> added two tools of galaxy_pycaret to usegalaxy.org

usegalaxy.org/annotation.yml.lock
=> update to latest version of egpax

usegalaxy.org/annotation.yml.lock
=> update to latest egapx

test.galaxyproject.org/chip_seq.yml.lock, test.galaxyproject.org/data_managers.yml.lock, test.galaxyproject.org/du_novo.yml.lock, test.galaxyproject.org/fasta_fastq.yml.lock, test.galaxyproject.org/get_data.yml.lock, test.galaxyproject.org/graph_display_data.yml.lock, test.galaxyproject.org/machine_learning.yml.lock, test.galaxyproject.org/multiple_alignments.yml.lock, test.galaxyproject.org/protein_modeling.yml.lock, test.galaxyproject.org/rna_seq.yml.lock, test.galaxyproject.org/spatial_omics.yml, test.galaxyproject.org/spatial_omics.yml.lock
@afgane we talked about this in the meeting. There's scripts/get_iwc_tools.py that takes a directory of workflows and attempts to guess the panel and writes out the necessary files.
=> Install tools for multiplex-tissue-imaging-TMA workflow on test

usegalaxy.org/assembly.yml, usegalaxy.org/assembly.yml.lock
=> Install FASTK tools

usegalaxy.org/annotation.yml.lock
=> updating version(s) fo EGAPx

usegalaxy.org/get_data.yml, usegalaxy.org/get_data.yml.lock
=> Install fastq-dl

usegalaxy.org/annotation.yml.lock
=> latest version of EGPAx

usegalaxy.org/annotation.yml.lock
=> latest version of egapx

usegalaxy.org/metagenomic_analysis.yml, usegalaxy.org/metagenomic_analysis.yml.lock
=> add checkm2

usegalaxy.org/fastq_quality_control.yml.lock
Update multiqc to the latest version
=> Update multiqc on main

usegalaxy.org/assembly.yml.lock
=> Update gfastsats to 1.3.9+galaxy2

usegalaxy.org/statistics.yml, usegalaxy.org/statistics.yml.lock
=> Adding rdeval

usegalaxy.org/fasta_fastq.yml.lock, usegalaxy.org/fastq_quality_control.yml.lock
=> Update cutadapt and multiqc on main

usegalaxy.org/statistics.yml.lock
=> Updating rdeval

usegalaxy.org/statistics.yml.lock
=> removing broken version of rdeval

usegalaxy.org/assembly.yml.lock
=> Removing broken version of halfdeep

README.md
updating is no longer needed, we update everything automatically
=> clarify and cleanup readme

README.md
=> more readme tweaks

usegalaxy.org/assembly.yml.lock
=> Update gfastats to 3.10

usegalaxy.org/ludwig_applications.yml.lock
As discussed with @natefoo updating the docker image tag version and fixing a bug found on Ludwig-Experiment
=> update to galaxy-ludwig latest version

test.galaxyproject.org/imaging.yml.lock, test.galaxyproject.org/spatial_omics.yml.lock
=> Update TMA tools

test.galaxyproject.org/rna_seq.yml.lock
=> Update featurecounts, need shed_data_table_conf.xml entry

usegalaxy.org/imaging.yml, usegalaxy.org/imaging.yml.lock
Adds imaging tools available on Test.
=> Add imaging tools

usegalaxy.org/sequence_contamination_filtering.yml.lock
=> updating NCBI FCS GX to v0.5.5

usegalaxy.org/annotation.yml.lock
=> Adding ability to save STAR alignments to EGAPx

.github/workflows/static.yml
=> updating action versions

usegalaxy.org/annotation.yml.lock
=> adding whitespace for a re-deploy :0

usegalaxy.org/annotation.yml.lock
=> updating egapx

usegalaxy.org/metagenomic_analysis.yml, usegalaxy.org/metagenomic_analysis.yml.lock
=> Install tools for MAG workflow

usegalaxy.org/fastq_quality_control.yml, usegalaxy.org/fastq_quality_control.yml.lock
=> Add falco to main

usegalaxy.org/single_cell.yml, usegalaxy.org/single_cell.yml.lock
Needed for one of the GTA tutorials
=> Add sceasy_convert to single_cell.yml

usegalaxy.org/statistics.yml.lock
=> adding new version of rdeval

usegalaxy.org/single_cell.yml, usegalaxy.org/single_cell.yml.lock
=> [GTA] add IUC Seurat tools

usegalaxy.org/metagenomic_analysis.yml, usegalaxy.org/metagenomic_analysis.yml.lock
Add the CoverM Contig tool for GTA for a GTN Tutorial
=> Add CoverM Contig and Kraken-Biom for GTA

usegalaxy.org/interactive_tools.yml.lock
Update an interactive tool -- data analysis agent/chatanalysis
=> update an interactive tool: data analysis agent

usegalaxy.org/imaging.yml, usegalaxy.org/imaging.yml.lock, usegalaxy.org/operate_on_genomic_intervals.yml.lock
=> Add live tools

test.galaxyproject.org/interactive_tools.yml, test.galaxyproject.org/interactive_tools.yml.lock
=> Add Physicell and RStudio ITs

usegalaxy.org/annotation.yml.lock, usegalaxy.org/statistics.yml.lock
=> Update egapx to v0.4.0-alpha

cloud/chip_seq.yml, cloud/chip_seq.yml.lock, cloud/deeptools.yml, cloud/deeptools.yml.lock, cloud/graph_display_data.yml, cloud/graph_display_data.yml.lock
=> [cloud] Add missing tools to run ATAC-seq wf

usegalaxy.org/annotation.yml.lock
=> Reinstall funtools annotate revisions

usegalaxy.org/annotation.yml.lock, usegalaxy.org/statistics.yml.lock
=> Update egapx to v0.4.1-alpha

usegalaxy.org/assembly.yml.lock
=> Update pairtools dedup

cloud/assembly.yml.lock, cloud/bed.yml.lock, cloud/datamash.yml.lock, cloud/fasta_fastq.yml.lock, cloud/fastq_quality_control.yml.lock, cloud/graph_display_data.yml.lock, cloud/mapping.yml.lock, cloud/nanopore.yml.lock, cloud/qiime2.yml.lock, cloud/rna_seq.yml.lock, cloud/sam_bam.yml.lock, cloud/single_cell.yml.lock, cloud/text_manipulation.yml.lock, cloud/variant_calling.yml.lock, cloud/virology.yml.lock
=> [cloud] Update cloud toolset to latest versions

cloud/machine_learning.yml, cloud/machine_learning.yml.lock
=> [cloud] Add Tabular Learner

usegalaxy.org/image_manipulation.yml, usegalaxy.org/image_manipulation.yml.lock
=> Add image manipulation tools in a new  "Image manipulation"  section on main

usegalaxy.org/mapping.yml.lock, usegalaxy.org/statistics.yml.lock
=> Update batched lastz

usegalaxy.org/assembly.yml, usegalaxy.org/assembly.yml.lock
=> install ragtag on main for reference guided assembly

usegalaxy.org/metagenomic_analysis.yml, usegalaxy.org/metagenomic_analysis.yml.lock
=> add mash dist tool to main

usegalaxy.org/annotation.yml.lock, usegalaxy.org/assembly.yml.lock, usegalaxy.org/metagenomic_analysis.yml, usegalaxy.org/metagenomic_analysis.yml.lock
=> Update pairtools, compleasm and mash

test.galaxyproject.org/lexicmap.yml, test.galaxyproject.org/lexicmap.yml.lock
=> Add lexicmap tool

usegalaxy.org/fasta_fastq.yml, usegalaxy.org/fasta_fastq.yml.lock
=> install seqkit split2 on main

usegalaxy.org/metagenomic_analysis.yml, usegalaxy.org/metagenomic_analysis.yml.lock
=> install mash paste on main
