.travis.yml
test.galaxyproject.org/chipseeker.yml.lock

The first attempt failed when rsyncing changes to the stratum 0, because the Travis console log size grew too large and the build was terminated.

Install ChIPseeker on Test (second attempt)

---

Makefile
README.md
requirements.txt
scripts/fix-lockfile.py
scripts/update-tool.py

- Support using make targets with a subset of tool definitions with `make TOOLSET=<toolshed_dir> <target>`
- Use `yaml.safe_load()` instead of `yaml.load()`
- Disable installation of TS dependencies by default

Tooling fixes

---

test.galaxyproject.org/snpeff.yml
test.galaxyproject.org/snpeff.yml.lock

manually created files atm since `make fix` creates https://github.com/galaxyproject/usegalaxy-tools/pull/30 but does not create the lock file for me.

add snpeff download 4.1.0

---

usegalaxy.org/compose_text_param.yml

This was breaking `make TOOLSET=usegalaxy.org lint` on my system, not sure how it was working for anyone else.
```
{py27}dave@gaius:~/github-repos/usegalaxy-tools $ make TOOLSET=usegalaxy.org lint
find ./usegalaxy.org -name '*.yml' | grep '^\./[^/]*/' | xargs -n 1 -P 8 python scripts/fix-lockfile.py
Traceback (most recent call last):
File "scripts/fix-lockfile.py", line 97, in <module>
update_file(args.fn.name)
File "scripts/fix-lockfile.py", line 40, in update_file
locked_tools = [x for x in locked['tools'] if x['name'] == tool['name'] and x['owner'] == tool['owner']]
KeyError: 'owner'
make: *** [Makefile:8: lint] Error 123
```

Fix incorrect YAML in compose_text_param.yml

---

.ci/jenkins.sh
.ci/repos.conf

There was a major complication to moving us to Jenkins: we are relying heavily on root VMs in Travis. I wanted to keep this process all unprivileged if possible since are Jenkins nodes are not transient, so this is the result. Now we work directly on the Stratum 0, even for trial builds (we just abort the transaction at the end). As long as the Jenkins job is configured to only run one build at a time this should be no problem, even if it's not as isolated as I'd like.
I think what makes the most sense is, instead of installing on merge, we should have @galaxybot run the script with `PUBLISH=true` whenever an authorized tool installer comments e.g. `@galaxybot deploy this`. This avoids any difficulty of trying to figure out what the changes in the PR are after merging, and it makes it …

Install in Jenkins

---

.schema.yml
scripts/fix-lockfile.py
scripts/update-tool.py

We have a no-TTS-in-production rule for usegalaxy.org, but do occasionally install from the TTS on test.galaxyproject.org. This will emit warnings if you specify a non-MTS TS URL, but removes the assumed/forced MTS.

Allow for the use of `tool_shed_url` in tool YAMLs

---

test.galaxyproject.org/du_novo.yml
test.galaxyproject.org/du_novo.yml.lock

Okay, I think I got it this time. I've added these tools to the existing `du_novo.yaml` file, and included the `.lock`.
- Attempt 1: #88
- Attempt 2: #89
---
These are a soon-to-be-published set of tools from Irene Tiemann-Boege's group at JKU.
They can be used to check the quality of duplex sequencing runs and find variants with more sensitivity than the standard analysis.

Duplex Analysis: Add to test.galaxyproject.org (attempt 3).

---

common_toolset/annotation.yml.lock
usegalaxy.org/annotation.yml.lock

~Adding `prokka@1.13+galaxy1`~
Adding `prokka@1.14.5`

Adding prokka@1.14.5

---

usegalaxy.org/evolution.yml
usegalaxy.org/evolution.yml.lock

The automated installer prematurely shut down the docker container, so the install database on cvmfs had `tn93` stuck at the cloning stage. I reset the state manually, so this _should_ install correctly. This also adds `tn93_readreduce` to the yaml and lock file, since that repository managed to install before the docker container shut down.

Remove suite, install tn93, add tn93_readreduce.

---

test.galaxyproject.org/variant_calling.yml.lock

This is a followup to #169 after I corrected issues in the tool pointed out by @mvdbeek.
I went ahead and made a new branch & PR to keep the commits simple.
This updates Variant Annotator on test.galaxyproject.org.

Update Variant Annotator to Python 3 version (2nd try)

---

usegalaxy.org/variant_calling.yml.lock

After testing on test.galaxyproject.org (#174), this version looks ready to be pushed out to Main.

Update Variant Annotator to Python 3 version on Main.

---

test.galaxyproject.org/variant_calling.yml.lock

I fixed a bug in the tool xml that I didn't catch last time (#173) until it was deployed to test.

Variant Annotator: Fix bug in previous update.

---

.ci/jenkins.sh

Updates to use https://hub.docker.com/layers/galaxy/galaxy-k8s/20.09/images/sha256-f607f66d7af6e568661e4f63d96cdeea8f5e5d655eb9873b5492dc64eae61ec0?context=explore

Update tool installer container to use 20.09 initial freeze image

---

test.galaxyproject.org/protein_modeling.yml.lock
usegalaxy.org/fasta_fastq.yml
usegalaxy.org/fasta_fastq.yml.lock
usegalaxy.org/protein_modeling.yml
usegalaxy.org/protein_modeling.yml.lock

PR requests to add three tools to main. `hhsearch`, `springsuite` (containing min-Z), and `splitfasta`. Tools are required for protein interaction prediction pipeline.

Add hhsearch, springsuite and splitfasta to usegalaxy.org

---

test.galaxyproject.org/assembly.yml
test.galaxyproject.org/assembly.yml.lock

Note: removing the tools from the YAML doesn't actually remove them, I did that manually beforehand, doing so just prevents this repo from reinstalling them.

[test.org] Remove TTS versions and update tools in Assembly section

---

usegalaxy.org/hyphy.yml.lock

Also removes revisions that were causing errors in the automated installer.

Update to HyPhy 2.5.26 on usegalaxy.org

---

test.galaxyproject.org/data_managers.yml
test.galaxyproject.org/data_managers.yml.lock

Generates reference data used in tutorials for smörgåsbord.

Install CustomProDB data manager on test.galaxyproject.org

---

usegalaxy.org/proteomics.yml.lock

Per @jmchilton "that would seem to be the best candidate" for the current tutorial. I'll also manually hide the 4.0.x version that's installed for now if this works.

Install a version of peptideshaker corresponding to search_gui 3.3.10.1

---

usegalaxy.org/proteomics.yml.lock

I also added the old versions that were listed back because I probably should not have removed them in the first place. `7fdd9119cc4f` includes the wrapper syntax fixes in galaxyproteomics/tools-galaxyp#419 but is before the major version change. I also removed `864bd76db767` and will remove this from usegalaxy.org manually since that version will never be runnable without manually fixing the wrapper.

Slightly upgrade peptideshaker on usegalaxy.org

---

usegalaxy.org/mapping.yml.lock

This update includes built-in reference sequences for SARS-CoV-2 genes.

Update bealign to 0.20.1 on usegalaxy.org

---

test.galaxyproject.org/du_novo.yml.lock

Old version is Python 2.7 and does not have deps in biocontainers.

Update duplex_family_size_distribution on test.org

---

usegalaxy.org/text_manipulation.yml.lock

Note you can't actually uninstall tools using this repo, I uninstalled the tools manually, this would just prevent them from being reinstalled on a future PR.

Prevent old non-working versin of regex_find_replace from being reinstalled

---

.ci/jenkins.sh
.github/CODEOWNERS
test.galaxyproject.org/chip_seq.yml.lock

Also:
- Drop non-org team from Codeowners so we don't annoy them since only .org is using this repo currently.
- Update Chip-SEQ section on test.org to test the version change.

Update Galaxy image version to 21.05

---

usegalaxy.org/chemicaltoolbox.yml
usegalaxy.org/chemicaltoolbox.yml.lock
usegalaxy.org/text_manipulation.yml
usegalaxy.org/text_manipulation.yml.lock

I have a PR open for some IWC workflows here: https://github.com/galaxyproject/iwc/pull/68
However, IWC testing is using the tools installed on usegalaxy.org (via CVMFS) and some of them are missing, so tests are failing. It would be great if these tools could be installed on .org.

Install tools for computational chemistry IWC workflows

---

usegalaxy.org/emboss.yml.lock

A user reported a problem with one of the EMBOSS tools (transeq) in [GHelp](https://help.galaxyproject.org/t/transeq-cannot-be-invoked-through-the-search-bar/7502). I think that it will fix the problem.

Emboss: update last version

---

usegalaxy.org/chemicaltoolbox.yml.lock

I removed all of the ChemicalToolBox from usegalaxy.org's `shed_tool_conf.xml` before deploying #492 and it seems that perhaps the CVMFS cache did not update properly when I did, because some tools were reported as already installed that should not have been. This should cause them to be reinstalled.

Bump ChemicalToolBox for missing tools

---

usegalaxy.org/variant_calling.yml.lock

I removed the two previous versions, we're actually going to hide this, we just want a version installed for seeing parameters of old runs and that sort of thing.

Update table_annovar on usegalaxy.org

---

test.galaxyproject.org/du_novo.yml.lock

This updates the Sequence Content Trimmer with a number of improvements made over the years which haven't yet been deployed.
Most importantly, it addresses an error reported on usegalaxy.org which was apparently due to the fact that it relied on Python 2.

Update the Sequence Content Trimmer to 0.2.3.

---

usegalaxy.org/statistics.yml
usegalaxy.org/statistics.yml.lock

Adds seqcomplexity tool to statistics list. It is a part of our initiative with the FDA to create reproducible metrics on raw reference sequence data. 
Tool can be found here
https://toolshed.g2.bx.psu.edu/view/iuc/seqcomplexity/f14a21f3d5b1

Adds seqcomplexity tool to statistics list

---

usegalaxy.org/variant_calling.yml
usegalaxy.org/variant_calling.yml.lock

Note this doesn't actually remove it (I will have to do that by hand), but it prevents it from being reinstalled after I remove it.
Fixes #569

Remove mixcr_analyze from usegalaxy.org

---

usegalaxy.org/machine_learning.yml
usegalaxy.org/machine_learning.yml.lock

This adds the `chopin2` tool to the Machine Learning panel in [usegalaxy.org](usegalaxy.org)
[https://toolshed.g2.bx.psu.edu/view/iuc/chopin2](https://toolshed.g2.bx.psu.edu/view/iuc/chopin2)

Add chopin2 to the Machine Learning panel

---

cloud/qiime2.yml
cloud/qiime2.yml.lock

Adding the [QIIME2 Galaxy tool suite](https://github.com/qiime2/galaxy-tools)[1] to cloud deployments with the `install_*` parameters set to `false` as the tools are all containerized. For the same PR to main, see #599
[1]: relevant datatype added to galaxy [in 22.05](https://github.com/galaxyproject/galaxy/pull/14216)

QIIME2 suite (for cloud deployments like AnVIL)

---

cloud/qiime2.yml.lock

per [this comment](https://github.com/galaxyproject/usegalaxy-tools/pull/600#issuecomment-1531561340) on the ill-fated #600, i've removed `tool_panel_section_id` and changed `install_repository_dependencies` to `true`

fixing borked cloud deployment update

---

usegalaxy.org/training_metabolomics.yml
usegalaxy.org/training_metabolomics.yml.lock

This PR adds the tools required for two Metabolomics training published in the GTN.
@natefoo let me know if something else is needed or has to be changed.

Add tools required for Metabolomics trainings for MS data processing

---

usegalaxy.org/chemicaltoolbox.yml.lock

Version 2.3 databases are now on CVMFS at `/cvmfs/data.galaxyproject.org/byhand/alphafold/2.3`
I removed the 2.1 version that's already installed from Main's `shed_tool_conf.xml` by hand since this never worked on .org due to the lack of databases.

Update AlphaFold on .org

---

usegalaxy.org/genome_diversity.yml
usegalaxy.org/genome_diversity.yml.lock

Most of these tools have been broken for a long time, they are tightly coupled with Galaxy internals (e.g. `galaxy.eggs`) as of 10 years ago and there is no support for updating them.
As always, this does not actually remove them, it just prevents them from being reinstalled after I remove them manually.

Remove Genome Diversity tools

---

usegalaxy.org/qiime2.yml
usegalaxy.org/qiime2.yml.lock

add qiime2 tools to Main into new section `QIIME2` (same as on eu)
list is the same as in https://github.com/usegalaxy-eu/usegalaxy-eu-tools/blob/eb1c8dde37973f586ff2a62941d85d306fe3b2e2/tools_q2d2.yaml

add qiime2 to main

---

usegalaxy.org/assembly.yml.lock

error from jenkins:
* Error installing a repository (after 0:00:00.102918 seconds)! Name: purge_dups,owner: iuc, revision: cf13a1e03e5b, error: {"err_msg": "No information is available for the requested repository revision.\nOne or more of the following parameter values is likely invalid: \ntool_shed_url: https://toolshed.g2.bx.psu.edu/\nname: purge_dups\nowner: iuc\nchangeset_revision: cf13a1e03e5b\n", "err_code": 400008}

remove revision of iuc/purge_dups that does not exist from main

---

usegalaxy.org/assembly.yml.lock

Found an error in pretext graph's wrapper, fixed but didn't update the version, so switching out for fixed wrapper

Switch to fixed version of pretext graph

---

usegalaxy.org/rna_seq.yml
usegalaxy.org/rna_seq.yml.lock

I would like to install brew3r_r on usegalaxy.org. This is a tool needed for [BREW3R](https://github.com/lldelisle/BREW3R) that will be presented at GCC2024.

Add brew3r_r

---

usegalaxy.org/assembly.yml
usegalaxy.org/assembly.yml.lock

Already available on .eu via bgruening toolshed.
I would also like to include the interactive tool to visualise blobtool runs, but I can't find this in the toolshed:
https://usegalaxy.eu/root?tool_id=interactive_tool_blobtoolkit

Add blobtoolkit to org

---

usegalaxy.org/proteomics.yml
usegalaxy.org/proteomics.yml.lock

Adds the **Validate FASTA Database** tool from GalaxyP.

Add Validate FASTA Database tool

---

usegalaxy.org/proteomics.yml
usegalaxy.org/proteomics.yml.lock

Adds the **FragPipe** tool from GalaxyP.

Add FragPipe Tool

---

usegalaxy.org/annotation.yml.lock

updating to latest version of ncbi-egapx

---

.ci/jenkins.sh
cloud/data_managers.yml
cloud/data_managers.yml.lock

Hopefully this will allow us to simply include `shed_tool_data_table_conf.xml` from CVFMS in the Galaxy Helm chart instead of shipping it with the chart, ensuring we have an in-sync config file with the pre-installed data managers.

[cloud] Update GALAXY_CONFIG_TOOL_DATA_PATH

---

usegalaxy.org/annotation.yml
usegalaxy.org/annotation.yml.lock

Adding the TAPScan tool, which is available on the European server but not on the main Org server, is needed for GTA to be available on the org server.
Since TAPScan works based on domain detection and gene family assignment for protein sequences, I wasn’t sure which .yml file would be most appropriate. I’m happy to take suggestions if there's a better fit.
Thank you so much,
Deepti Varshney

add tool : Tapscan

---

usegalaxy.org/annotation.yml
usegalaxy.org/annotation.yml.lock
usegalaxy.org/mapping.yml.lock

Why we need to import existing and maintained tools into the IUC, and why do we not at least keep the TS owner? 😩

Install staramr from iuc

---

usegalaxy.org/machine_learning.yml
usegalaxy.org/machine_learning.yml.lock

We’ve renamed the tool ID from `pycaret_compare` (as already installed on usegalaxy.org) to `tabular_learner` to reflect our shift toward a dataset-type-oriented tool rather than a package-oriented one. We may later use packages such as `AutoGluon` to update `tabular_learner`, so renaming the tool ID now makes sense. We will deprecate `pycaret_compare` once `tabular_learner` is installed.
If it’s helpful for review, the code for `tabular_learner` is identical to that of `pycaret_compare`.

add tabular_learner

---

usegalaxy.org/proteomics.yml
usegalaxy.org/proteomics.yml.lock

We would like to add the reactome pathway analysis official CLI tool and Galaxy integration to usegalaxy.org. This tool includes all pathway analysis available via our web APIs and integration with the ReactomeGSA R tooling.

Add Reactome CLI

---

usegalaxy.org/data_managers.yml
usegalaxy.org/data_managers.yml.lock
usegalaxy.org/metagenomic_analysis.yml
usegalaxy.org/metagenomic_analysis.yml.lock

- iphop_predict is already on usegalaxy.eu
- phi_toolkit_report and defense_finder have been tested on my instance with a workflow that I want to submit to IWC

Add more tools for analyzing virus/phage in metagenomics
